import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NavigationBar} from "@/src/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        {/* The 'flex' class forces the Sidebar and the main content to sit side-by-side */}
        <div className="flex min-h-screen">
          
          {/* Navbar component */}
          <aside className="w-48 bg-slate-900 text-white fixed h-screen">
            <NavigationBar />
          </aside>

          {/* The 'children' is page.tsx content. */}
          <main className="flex-1 pl-48 bg-slate-50">
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
